### PR TITLE
add dhcpcd and links web browser

### PR DESCRIPTION
**Pull request by ghost**
test it

### CODE REVIEW

**Review by antoniusmisfit — CHANGES_REQUESTED** [review]
I get this on compilation:

+ make busybox install -j5
scripts/kconfig/conf -s Config.in
#
# using defaults found in .config
#
  SPLIT   include/autoconf.h -> include/config/*
  HOSTCC  applets/usage
  HOSTCC  applets/applet_tables
  GEN     include/bbconfigopts.h
  GEN     include/common_bufsiz.h
  GEN     include/usage_compressed.h
  GEN     include/applet_tables.h include/NUM_APPLETS.h
  GEN     include/applet_tables.h include/NUM_APPLETS.h
  HOSTCC  applets/usage_pod
  CC      applets/applets.o
gcc: error: unrecognized command line option '-0s'; did you mean '-Os'?
make[1]: *** [scripts/Makefile.build:198: applets/applets.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:372: applets_dir] Error 2

**Comment by ghost** [comment]
replace -0s to -Os

**Comment by antoniusmisfit** [comment]
If I remember correctly from compiling Ivan Davidov's distro with links, it requires a C library to be installed as well(either musl or glibc). I'll have to take a close look at Ivan's code for that. And Busybox includes DHCP server and client applets, so compiling separate DHCP software may not be necessary.

**Comment by ghost** [comment]
But all is static and you don't need a libc

**Comment by ghost** [comment]
so?

**Comment by antoniusmisfit** [comment]
I'll merge and test this again.

**Pull request merged**
