### PR TITLE
make it simple and kernel upgrade

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by antoniusmisfit — APPROVED** [review]

**Comment by antoniusmisfit** [comment]
This is definitely cleaner. I'll approve this now and test it tonight after work.

**Comment by antoniusmisfit** [comment]
The kernel won't build now. I'll try reverting the kernel version to what I had before. If that doesn't work, I'll have to totally revert to before the merge and work the changes in carefully.

**Comment by ghost** [comment]
What error message?

**Comment by antoniusmisfit** [comment]
Also, removing all the directories within the build script before making them erases the feature of using pre-downloaded sources to speed up subsequent builds, so I'll have to reimplement that feature now. Otherwise, this is an improvement.

**Pull request merged**
